### PR TITLE
Revert "Bug: reference to db models"

### PR DESCRIPTION
**Pull request by unrealkaii**
Reverts chingu-voyage7/Bears-Team-17#10

### CODE REVIEW

**Comment by unrealkaii** [comment]
there were merge conflicts on the linting PR i thought merging this pr caused that. So kindly approve this pr so i can merge again

**Comment by nikrb** [comment]
EDIT: I have fixed the merge conflict on #6 
Can we get #6 reviewed and merged and if everything's ok close this?

not sure this is a good idea dude. I'll have a look at the merge conflicts.

**Comment by unrealkaii** [comment]
@nikrb i have successfully merged it so can you approve this one so we merge?

**Comment by nikrb** [comment]
default branch is currently correct. This pr creates incorrect model schema so I will close it.

**Pull request closed without merging**
